export const getProductInfoQuery = /* GraphQL */ `
  query AllProducts($input: [FilterHomeCategoriesInput]) {
    allProducts(input: $input) {
      paginatorInfo {
        count
        currentPage
        lastPage
        total
      }
      data {
        id
        sku
        type
        parentId
        attributeFamilyId
        productNumber
        name
        shortDescription
        description
        urlKey
        shareURL
        new
        featured
        status
        guestCheckout
        visibleIndividually
        metaTitle
        metaKeywords
        metaDescription
        price
        specialPrice
        specialPriceFrom
        specialPriceTo
        weight
        createdAt
        updatedAt
        isInWishlist
        isInSale
        isSaleable
        averageRating
        percentageRating
        reviews {
          id
          name
          title
          rating
          comment
          status
          productId
          customerId
          createdAt
          updatedAt
          customer {
            id
            firstName
            lastName
            name
            gender
            dateOfBirth
            email
            phone
            image
            imageUrl
            status
            password
            apiToken
            customerGroupId
            channelId
            subscribedToNewsLetter
            isVerified
            isSuspended
            token
            rememberToken
            createdAt
            updatedAt
            isWishlistShared
            getWishlistSharedLink
          }
          images {
            id
            reviewId
            type
            mimeType
            path
            url
            review {
              id
              name
              title
              rating
              comment
              status
              productId
              customerId
              createdAt
              updatedAt
            }
          }
        }
        additionalData {
          id
          code
          label
          value
          admin_name
          type
        }
      }
    }
  }
`;
