export const cartInfoFragment = /* GraphQL */ `
  fragment cartInfo on Cart {
    id
    customerEmail
    customerFirstName
    customerLastName
    grandTotal
    baseGrandTotal
    subTotal
    baseSubTotal
    taxTotal
    baseTaxTotal
    discountAmount
    baseDiscountAmount
    customerId
    createdAt
    updatedAt
    addresses {
      id
      cartId
      addressType
      customerId
      firstName
      lastName
      gender
      companyName
      address1
      address2
      postcode
      city
      state
      country
      email
      phone
      defaultAddress
      vatId
    }
    selectedShippingRate {
      id
      carrier
      carrierTitle
      method
      methodTitle
      methodDescription
      price
      basePrice
      discountAmount
      baseDiscountAmount
    }
    payment {
      id
      method
      methodTitle
    }
    items {
      id
      quantity
      sku
      type
      name
      couponCode
      weight
      totalWeight
      baseTotalWeight
      price
      basePrice
      total
      baseTotal
      taxPercent
      taxAmount
      baseTaxAmount
      discountPercent
      discountAmount
      baseDiscountAmount
      additional
      parentId
      productId
      cartId
      taxCategoryId
      customPrice
      appliedCartRuleIds
      createdAt
      updatedAt
      product {
        id
        type
        attributeFamilyId
        sku
        parentId
        images {
          id
          path
          url
        }
        productFlats {
          id
          sku
          name
          description
          shortDescription
          urlKey
          new
          featured
          status
          visibleIndividually
          thumbnail
          price
          cost
          specialPrice
          specialPriceFrom
          specialPriceTo
          weight
          color
          colorLabel
          size
          sizeLabel
          locale
          channel
          productId
          parentId
          minPrice
          maxPrice
          metaTitle
          metaKeywords
          metaDescription
          width
          height
          depth
          variants {
            id
            sku
            name
            description
            shortDescription
            urlKey
            new
            featured
            status
            visibleIndividually
            thumbnail
            price
            locale
            channel
            productId
            parentId
          }
          parent {
            id
            sku
            name
            description
            shortDescription
            urlKey
            new
            featured
            status
            visibleIndividually
            thumbnail
            price
            cost
            specialPrice
            specialPriceFrom
            specialPriceTo
            weight
          }
          createdAt
          updatedAt
        }
      }
    }
  }
`
